### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by LovesAsuna** [Vankka/ForgeIconPlus#3]
https://pastebin.com/pesp1Xwb

**Comment by Vankka** [comment]
Please try this & tell me how it goes, and if the icons on the server page change

[ForgeIconPlus-1.3.zip](https://github.com/Vankka/ForgeIconPlus/files/3134307/ForgeIconPlus-1.3.zip)

**Comment by LovesAsuna** [comment]
Actually this error does not happen often, it just happens sometimes
In addition, the icon has changed.

**Comment by Vankka** [comment]
Alright, I added extra null checks so it shouldn't happen again

**Comment by Vankka** [comment]
The jar i gave you before may not work, you should get https://github.com/Vankka/ForgeIconPlus/releases/tag/v1.4 instead
